name: nexema_generator
description: Command line app used to generate Dart code from .nex files
version: 0.1.0
repository: https://github.com/nexema/dart

environment:
  sdk: ">=2.18.0 <3.0.0"

executables:
  nexema_generator:

dev_dependencies:
  build_runner: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
  dart_mappable_builder: ^3.1.2
  observable: ^0.24.0

dependencies:
  code_builder: ^4.3.0
  dart_mappable: ^3.1.2
  dart_style: ^2.2.4
  meta: ^1.9.0
  path: ^1.8.2
  recase: ^4.1.0
