name: nexema
description: Nexema's dart runtime library.
version: 1.0.1
repository: https://github.com/nexema/dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  fast_immutable_collections: ^8.1.1
  pool: ^1.5.1

dev_dependencies:
  test: ^1.20.1
  flutter_lints: ^1.0.0
  benchmark: ^0.3.0
